language: node_js
node_js: 11
scripts:
  - npm run lint && npm run test && npm run build

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target-branch: master
  local_dir: build
  on:
    branch: develop
